activeWorkspaceOnFocusChange = true
alternativeDisplays = ''
centerCursorOnFocusChange = false
centerCursorOnWorkspaceChange = false
changeWorkspaceOnAppAssign = true
checkForUpdatesAutomatically = false
displayMode = 'dynamic'
enableFocusManagement = true
enableIntegrations = false
enablePictureInPictureSupport = true
enableSpaceControl = true
enableSpaceControlAnimations = true
enableSpaceControlTilesAnimations = true
enableSwipeGestures = true
enableWorkspaceTransitions = false
focusFrontmostWindow = false
focusNextWorkspaceWindow = 'cmd+]'
focusPreviousWorkspaceWindow = 'cmd+['
keepUnassignedAppsOnSwitch = false
loopWorkspaces = true
menuBarDisplayAliases = ''
menuBarTitleTemplate = '$WORKSPACE'
pipApps = []
pipScreenCornerOffset = 15
restartAppOnWakeUp = false
restoreHiddenAppsOnSwitch = true
runScriptAfterWorkspaceChange = ''
runScriptOnLaunch = ''
runScriptOnProfileChange = 'sketchybar --reload'
runScriptOnWorkspaceChange = 'sketchybar --trigger flashspace_workspace_change WORKSPACE="$WORKSPACE" DISPLAY="$DISPLAY"'
showFloatingNotifications = true
showMenuBarIcon = true
showMenuBarTitle = true
showSpaceControl = 'cmd+`'
skipEmptyWorkspacesOnSwitch = false
spaceControlCurrentDisplayWorkspaces = false
spaceControlHideEmptyWorkspaces = false
spaceControlNumberOfColumns = 0
spaceControlUpdateScreenshotsOnOpen = false
swipeDown3FingerAction = 'none'
swipeDown4FingerAction = 'none'
swipeLeft3FingerAction = 'previousWorkspace'
swipeLeft4FingerAction = 'none'
swipeRight3FingerAction = 'nextWorkspace'
swipeRight4FingerAction = 'none'
swipeThreshold = 0.20000000000000001
swipeUp3FingerAction = 'none'
swipeUp4FingerAction = 'none'
switchWorkspaceWhenPipCloses = true
workspaceTransitionDimming = 0.20000000000000001
workspaceTransitionDuration = 0.29999999999999999

[[floatingApps]]
bundleIdentifier = 'com.apple.systempreferences'
iconPath = '/System/Applications/System Settings.app/Contents/Resources/SystemSettings.icns'
name = 'System Settings'

[[floatingApps]]
bundleIdentifier = 'com.anthropic.claudefordesktop'
iconPath = '/Applications/Claude.app/Contents/Resources/electron.icns'
name = 'Claude'